# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL (DOCKER)
spring.datasource.url=jdbc:postgresql://localhost:5433/movierec_db
spring.datasource.username=postgres
spring.datasource.password=postgres_root

# DRIVER Y DIALECTO DE JPA PARA POSTGRES
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ESTRATEGIA DE CREACIÓN DE TABLAS
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola de IntelliJ
spring.jpa.show-sql=true

# CONFIGURACIÓN DEL SERVIDOR DE EMAIL (MAILPIT EN DOCKER)
spring.mail.host=127.0.0.1
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false