# CONFIGURACIÓN DE BASE DE DATOS PERSISTENTE (MODO ARCHIVO)
# Se creará una carpeta llamada 'data' en la raíz de tu proyecto con el archivo de la DB
spring.datasource.url=jdbc:h2:file:./data/cinemadb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola para verificar los datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Esto es CRUCIAL si usas Spring Security para que te deje ver las tablas
spring.h2.console.settings.web-allow-others=true

# Mostrar lo que hace Spring en la consola
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
